HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_INVALID_REQUEST = 400
HTTP_OK = 200
PORT = 10999

ONLINE_REGISTRATION_ERROR = -1

WRONG_ARGUMENTS = -1

mongoIp = "127.0.0.1"
#deploy port
mongoPort = 27017

host = 'mongodb://127.0.0.1/meetings'


#MONGO DB ERRORS
DB_NOT_CONNECTED = "Could not connect to MongoDB"


# MEETINGS INTERACTIONS and SURVEY
MEETINGS_INTERACTIONS_RECORDERD = 200
MEETINGS_INTERACTIONS_ERROR = -1

MEETINGS_SURVEY_RECORDERD = 200
MEETINGS_SURVEY_ERROR = -1

# SUMMARY
SUMMARY_SENT = 200
SUMMARY_ERROR = -1
